package com.syavelanisrina.projectakhirpbo;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Booking extends javax.swing.JFrame {
    private String nama, email, telepon, ktp, asal, tujuan, tanggal;
    private int jumlahPenumpang;
    
    private Map<String, Class<? extends JFrame>> tiketMap;
    /**
     * Creates new form Main
     */
    public Booking(String nama, String email, String telepon, String ktp, String asal, String tujuan, String tanggal) {
        this.nama = nama;
        this.email = email;
        this.telepon = telepon;
        this.ktp = ktp;
        this.asal = asal;
        this.tujuan = tujuan;
        this.tanggal = tanggal;
        initComponents();
        initializeTiketMap();
    }
    
    public Booking(String nama, String email, String telepon, String ktp) {
    this.nama = nama;
    this.email = email;
    this.telepon = telepon;
    this.ktp = ktp;
    initComponents();
    initializeTiketMap(); // Pastikan peta tiket tetap diinisialisasi
}

    private void initializeTiketMap() {
        tiketMap = new HashMap<>();

        // Bandung (BD) sebagai kota asal
        tiketMap.put("Bandung-Semarang", DaftarTiketBDSMT.class);
        tiketMap.put("Bandung-Jakarta", DaftarTiketBDGMR.class);
        tiketMap.put("Bandung-Yogyakarta", DaftarTiketBDYK.class);
        tiketMap.put("Bandung-Solo", DaftarTiketBDSLO.class);
        tiketMap.put("Bandung-Bekasi", DaftarTiketBandungBekasi.class);
        tiketMap.put("Bandung-Surabaya", DaftarTiketBandungSurabaya.class);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asalL = new javax.swing.JLabel();
        tujuanL = new javax.swing.JLabel();
        tanggalPergiL = new javax.swing.JLabel();
        penumpangL = new javax.swing.JLabel();
        titleL = new javax.swing.JLabel();
        penumpangTF = new javax.swing.JTextField();
        tanggalTF = new javax.swing.JTextField();
        calenderIcon = new javax.swing.JLabel();
        markerIcon1 = new javax.swing.JLabel();
        markerIcon2 = new javax.swing.JLabel();
        sitIcon = new javax.swing.JLabel();
        cariTiketB = new javax.swing.JButton();
        dariComboBox = new javax.swing.JComboBox<>();
        keComboBox = new javax.swing.JComboBox<>();
        toDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        asalL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        asalL.setText("Dari");

        tujuanL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tujuanL.setText("Ke");

        tanggalPergiL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tanggalPergiL.setText("Tanggal Pergi");

        penumpangL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        penumpangL.setText("Penumpang");

        titleL.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titleL.setText("PEMESANAN TIKET");

        penumpangTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penumpangTFActionPerformed(evt);
            }
        });

        tanggalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalTFActionPerformed(evt);
            }
        });

        calenderIcon.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        calenderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/calendar2.png"))); // NOI18N

        markerIcon1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        markerIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/pngegg.png"))); // NOI18N

        markerIcon2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        markerIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/pngegg.png"))); // NOI18N

        sitIcon.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        sitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/penumpang.png"))); // NOI18N

        cariTiketB.setBackground(new java.awt.Color(153, 255, 51));
        cariTiketB.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cariTiketB.setForeground(new java.awt.Color(0, 0, 0));
        cariTiketB.setText("Next");
        cariTiketB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTiketBActionPerformed(evt);
            }
        });

        dariComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandung" }));
        dariComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dariComboBoxActionPerformed(evt);
            }
        });

        keComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Bekasi", "Semarang", "Solo", "Yogyakarta", "Surabaya" }));
        keComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keComboBoxActionPerformed(evt);
            }
        });

        toDetail.setBackground(new java.awt.Color(255, 0, 0));
        toDetail.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        toDetail.setForeground(new java.awt.Color(0, 0, 0));
        toDetail.setText("Back");
        toDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(tujuanL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(calenderIcon)
                        .addGap(6, 6, 6)
                        .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(keComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(asalL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(tanggalPergiL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(penumpangL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(penumpangTF, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(markerIcon1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(dariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(titleL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(markerIcon2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(cariTiketB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(sitIcon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(toDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(tujuanL)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calenderIcon)
                            .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(keComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(asalL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(tanggalPergiL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(penumpangL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(penumpangTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(markerIcon1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(dariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(titleL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(markerIcon2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(615, 615, 615)
                        .addComponent(cariTiketB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(sitIcon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(615, 615, 615)
                        .addComponent(toDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public Booking(){
        
    }
    
    private void penumpangTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penumpangTFActionPerformed

    }//GEN-LAST:event_penumpangTFActionPerformed

    
    private void tanggalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalTFActionPerformed

    }//GEN-LAST:event_tanggalTFActionPerformed

    private void cariTiketBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTiketBActionPerformed
        String asal = dariComboBox.getSelectedItem().toString();
        String tujuan = keComboBox.getSelectedItem().toString();
        String tanggal = tanggalTF.getText();
        String penumpangStr = penumpangTF.getText();

        try {
            jumlahPenumpang = Integer.parseInt(penumpangStr);
            if (jumlahPenumpang <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah penumpang harus berupa angka positif.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (asal.equals(tujuan)) {
            JOptionPane.showMessageDialog(this, "Asal dan tujuan tidak boleh sama!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Pastikan showTiketFrame menerima `jumlahPenumpang`
        showTiketFrame(asal, tujuan, tanggal);
    }//GEN-LAST:event_cariTiketBActionPerformed

    private boolean isValidDate(String date) {
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    sdf.setLenient(false);
    try {
        Date parsedDate = sdf.parse(date); // Parse untuk memastikan validitas
        return true;
    } catch (ParseException e) {
        return false;
    }
}
    
    private void showTiketFrame(String asal, String tujuan, String tanggal) {
        String key = asal + "-" + tujuan;
        Class<? extends JFrame> tiketFrameClass = tiketMap.get(key);

        if (tiketFrameClass != null) {
            try {
                JFrame tiketFrame = tiketFrameClass
                    .getDeclaredConstructor(String.class, String.class, String.class, String.class, String.class, String.class, String.class, int.class, String.class)
                    .newInstance(nama, email, telepon, ktp, asal, tujuan, tanggal, jumlahPenumpang, "Kereta Papandayan");
                tiketFrame.setVisible(true);
                this.dispose(); // Tutup frame Booking
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membuka frame tiket.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada tiket untuk rute tersebut.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void dariComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dariComboBoxActionPerformed
        if (dariComboBox.getSelectedItem() != null && dariComboBox.getSelectedItem().equals(keComboBox.getSelectedItem())) {
            javax.swing.JOptionPane.showMessageDialog(Booking.this, 
                "Asal dan tujuan tidak boleh sama!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            dariComboBox.setSelectedIndex(0); // Atur ulang ComboBox asal
        }
    }//GEN-LAST:event_dariComboBoxActionPerformed

    private void keComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keComboBoxActionPerformed
        if (keComboBox.getSelectedItem() != null && keComboBox.getSelectedItem().equals(dariComboBox.getSelectedItem())) {
            javax.swing.JOptionPane.showMessageDialog(Booking.this, 
                "Asal dan tujuan tidak boleh sama!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            keComboBox.setSelectedIndex(0); // Atur ulang ComboBox tujuan
        }
    }//GEN-LAST:event_keComboBoxActionPerformed

    private void toDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDetailActionPerformed
    DetailPemesanan detailpemesanan = new DetailPemesanan();
    detailpemesanan.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_toDetailActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asalL;
    private javax.swing.JLabel calenderIcon;
    private javax.swing.JButton cariTiketB;
    private javax.swing.JComboBox<String> dariComboBox;
    private javax.swing.JComboBox<String> keComboBox;
    private javax.swing.JLabel markerIcon1;
    private javax.swing.JLabel markerIcon2;
    private javax.swing.JLabel penumpangL;
    private javax.swing.JTextField penumpangTF;
    private javax.swing.JLabel sitIcon;
    private javax.swing.JLabel tanggalPergiL;
    private javax.swing.JTextField tanggalTF;
    private javax.swing.JLabel titleL;
    private javax.swing.JButton toDetail;
    private javax.swing.JLabel tujuanL;
    // End of variables declaration//GEN-END:variables
}
