package com.syavelanisrina.projectakhirpbo;

import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;

import java.awt.Button;
public class DaftarTiketBDGMR extends javax.swing.JFrame implements DaftarTiket{
    private String nama, email, telepon, ktp, asal, tujuan, tanggal, namaKereta;
    private int jumlahPenumpang;

    public DaftarTiketBDGMR(String nama, String email, String telepon, String ktp, String asal, String tujuan, String tanggal, int jumlahPenumpang, String namaKereta) {
        this.nama = nama;
        this.email = email;
        this.telepon = telepon;
        this.ktp = ktp;
        this.asal = asal;
        this.tujuan = tujuan;
        this.tanggal = tanggal;
        this.jumlahPenumpang = jumlahPenumpang; // Pastikan variabel ini diatur
        this.namaKereta = namaKereta;
        initComponents();
    }
     
     @Override
     public int getHarga(){
         return 250000;
     }
     
     @Override
     public String getNamaTiket() {
         return "Bandung - Jakarta";
     }

     @Override
     public String getNamaKereta(){
         return "Kereta Papandayan";
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        bdgmrRB = new javax.swing.JRadioButton();
        toPaymentB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Papandayan\n\n14:39   BANDUNG (BD)\n '\n '\n17:49   GAMBIR (GMR)                                 Rp 250.000 /pax");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Daftar Tiket");

        toPaymentB.setBackground(new java.awt.Color(153, 255, 51));
        toPaymentB.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        toPaymentB.setForeground(new java.awt.Color(0, 0, 0));
        toPaymentB.setText("Next");
        toPaymentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPaymentBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toPaymentB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(bdgmrRB)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bdgmrRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(toPaymentB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toPaymentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPaymentBActionPerformed
        if (bdgmrRB.isSelected()) {
            int totalHarga = getHarga() * jumlahPenumpang; // Kalkulasi total harga
            Payment payment = new Payment(nama, email, telepon, ktp, asal, tujuan, tanggal, totalHarga, jumlahPenumpang, getNamaKereta());
            payment.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih tiket terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_toPaymentBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDGMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDGMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDGMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDGMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarTiketBDGMR("Nama", "Email", "Telepon", "KTP", "Bandung", "Jakarta", "01-01-2024", 1, "Kereta Papandayan").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bdgmrRB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton toPaymentB;
    // End of variables declaration//GEN-END:variables
}
