package com.syavelanisrina.projectakhirpbo;

import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;

public class DaftarTiketBDSLO extends javax.swing.JFrame implements DaftarTiket {
    private String nama, email, telepon, ktp, asal, tujuan, tanggal, namaKereta;
    private int jumlahPenumpang;

    public DaftarTiketBDSLO(String nama, String email, String telepon, String ktp, String asal, String tujuan, String tanggal, int jumlahPenumpang, String namaKereta) {
        this.nama = nama;
        this.email = email;
        this.telepon = telepon;
        this.ktp = ktp;
        this.asal = asal;
        this.tujuan = tujuan;
        this.tanggal = tanggal;
        this.jumlahPenumpang = jumlahPenumpang;
        this.namaKereta = namaKereta;
        initComponents();
    }
    
    @Override
    public int getHarga() {
        return 250000;
    }

    @Override
    public String getNamaTiket() {
        return "Bandung - Solo";
    }

    @Override
    public String getNamaKereta() {
        return "Kereta Lodaya";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        RBlodaya = new javax.swing.JRadioButton();
        toPayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("LODAYA\n\n06:55   BANDUNG (BD)\n '\n '\n14:50   SOLO BALAPAN (SLO)                      Rp 250.000 /pax");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Daftar Tiket");

        toPayment.setBackground(new java.awt.Color(153, 255, 51));
        toPayment.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        toPayment.setForeground(new java.awt.Color(0, 0, 0));
        toPayment.setText("Next");
        toPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(RBlodaya)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(186, 186, 186)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(RBlodaya)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addComponent(toPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPaymentActionPerformed
        if (RBlodaya.isSelected()) {
            int totalHarga = getHarga() * jumlahPenumpang;
            Payment payment = new Payment(nama, email, telepon, ktp, asal, tujuan, tanggal, totalHarga, jumlahPenumpang, getNamaKereta());
            payment.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih tiket terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_toPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDSLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDSLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDSLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarTiketBDSLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarTiketBDSLO("Nama", "Email", "Telepon", "KTP", "Bandung", "Solo", "01-01-2024", 1, "Kereta Lodaya").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBlodaya;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton toPayment;
    // End of variables declaration//GEN-END:variables
}
