/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.syavelanisrina.projectakhirpbo;

/**
 *
 * @author shifa
 */
public class DaftarTiketGMRSLO extends javax.swing.JFrame {

    /**
     * Creates new form DaftarTiket
     */
    public DaftarTiketGMRSLO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GambirSolo1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        GambirSolo2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        GambirSolo3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        GambirSolo4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        GambirSolo5 = new javax.swing.JTextArea();
        btnGambirSolo1 = new javax.swing.JRadioButton();
        btnGambirSolo2 = new javax.swing.JRadioButton();
        btnGambirSolo3 = new javax.swing.JRadioButton();
        btnGambirSolo4 = new javax.swing.JRadioButton();
        btnGambirSolo5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Daftar Tiket");

        GambirSolo1.setColumns(20);
        GambirSolo1.setRows(5);
        GambirSolo1.setText("Manahan\n\n12:13   GAMBIR (GMR\n '\n '\n19:40   SOLO BALAPAN (SLO)\t               Rp 580.000 /pax");
        jScrollPane1.setViewportView(GambirSolo1);

        GambirSolo2.setColumns(20);
        GambirSolo2.setRows(5);
        GambirSolo2.setText("Argo Lawu\n\n20:45   GAMBIR (GMR\n '\n '\n03:40   SOLO BALAPAN (SLO)\t               Rp 650.000 /pax");
        jScrollPane2.setViewportView(GambirSolo2);

        GambirSolo3.setColumns(20);
        GambirSolo3.setRows(5);
        GambirSolo3.setText("Argo Dwipangga\n\n20:30   SOLO BALAPAN (SLO)\n '\n '\n03:30   GAMBIR (GMR)\t               Rp 650.000 /pax");
        jScrollPane3.setViewportView(GambirSolo3);

        GambirSolo4.setColumns(20);
        GambirSolo4.setRows(5);
        GambirSolo4.setText("Gajayana\n\n18:50   GAMBIR (GMR\n '\n '\n02:12   SOLO BALAPAN (SLO)\t               Rp 760.000 /pax");
        jScrollPane4.setViewportView(GambirSolo4);

        GambirSolo5.setColumns(20);
        GambirSolo5.setRows(5);
        GambirSolo5.setText("Bima\n\n17:00   GAMBIR (GMR\n '\n '\n00:13   SOLO BALAPAN (SLO)\t               Rp 730.000 /pax");
        jScrollPane5.setViewportView(GambirSolo5);

        btnGambirSolo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambirSolo1ActionPerformed(evt);
            }
        });

        btnGambirSolo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambirSolo2ActionPerformed(evt);
            }
        });

        btnGambirSolo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambirSolo3ActionPerformed(evt);
            }
        });

        btnGambirSolo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambirSolo4ActionPerformed(evt);
            }
        });

        btnGambirSolo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambirSolo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGambirSolo1)
                    .addComponent(btnGambirSolo2)
                    .addComponent(btnGambirSolo3)
                    .addComponent(btnGambirSolo4)
                    .addComponent(btnGambirSolo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnGambirSolo1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnGambirSolo2)
                        .addGap(97, 97, 97)
                        .addComponent(btnGambirSolo3)
                        .addGap(97, 97, 97)
                        .addComponent(btnGambirSolo4)
                        .addGap(97, 97, 97)
                        .addComponent(btnGambirSolo5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGambirSolo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambirSolo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGambirSolo1ActionPerformed

    private void btnGambirSolo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambirSolo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGambirSolo2ActionPerformed

    private void btnGambirSolo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambirSolo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGambirSolo3ActionPerformed

    private void btnGambirSolo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambirSolo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGambirSolo4ActionPerformed

    private void btnGambirSolo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambirSolo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGambirSolo5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarTiketGMRSLO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea GambirSolo1;
    private javax.swing.JTextArea GambirSolo2;
    private javax.swing.JTextArea GambirSolo3;
    private javax.swing.JTextArea GambirSolo4;
    private javax.swing.JTextArea GambirSolo5;
    private javax.swing.JRadioButton btnGambirSolo1;
    private javax.swing.JRadioButton btnGambirSolo2;
    private javax.swing.JRadioButton btnGambirSolo3;
    private javax.swing.JRadioButton btnGambirSolo4;
    private javax.swing.JRadioButton btnGambirSolo5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
