package com.syavelanisrina.projectakhirpbo;

import javax.swing.JOptionPane;

public class DetailPemesanan extends javax.swing.JFrame {

    public DetailPemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailtitleL = new javax.swing.JLabel();
        namaL = new javax.swing.JLabel();
        emailL = new javax.swing.JLabel();
        teleponL = new javax.swing.JLabel();
        ktpL = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        ktpTF = new javax.swing.JTextField();
        teleponTF = new javax.swing.JTextField();
        cariTiketB1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        detailtitleL.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        detailtitleL.setForeground(new java.awt.Color(255, 255, 255));
        detailtitleL.setText("DETAIL PEMESANAN");

        namaL.setBackground(new java.awt.Color(255, 255, 255));
        namaL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        namaL.setText("Nama");

        emailL.setBackground(new java.awt.Color(255, 255, 255));
        emailL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        emailL.setText("Email");

        teleponL.setBackground(new java.awt.Color(255, 255, 255));
        teleponL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        teleponL.setText("No Telepon");

        ktpL.setBackground(new java.awt.Color(255, 255, 255));
        ktpL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ktpL.setText("No KTP");

        namaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTFActionPerformed(evt);
            }
        });

        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        ktpTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktpTFActionPerformed(evt);
            }
        });

        teleponTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponTFActionPerformed(evt);
            }
        });

        cariTiketB1.setBackground(new java.awt.Color(153, 255, 51));
        cariTiketB1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cariTiketB1.setForeground(new java.awt.Color(0, 0, 0));
        cariTiketB1.setText("Next");
        cariTiketB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTiketB1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/nama.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/email.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/nomorTelepon.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/Resource/ktp.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(detailtitleL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(teleponTF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ktpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(namaL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ktpL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(emailL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(cariTiketB1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(teleponL)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(detailtitleL)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(teleponTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(ktpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(namaL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(ktpL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(emailL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(612, 612, 612)
                        .addComponent(cariTiketB1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(teleponL)))
                .addGap(125, 125, 125))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTFActionPerformed
        String nama = namaTF.getText();
        namaTF.setText(nama.toUpperCase());
    }//GEN-LAST:event_namaTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed

    }//GEN-LAST:event_emailTFActionPerformed

    private void ktpTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktpTFActionPerformed

    }//GEN-LAST:event_ktpTFActionPerformed

    private void teleponTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponTFActionPerformed

    }//GEN-LAST:event_teleponTFActionPerformed

    private void cariTiketB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTiketB1ActionPerformed
        String nama = namaTF.getText();
        String email = emailTF.getText();
        String telepon = teleponTF.getText();
        String ktp = ktpTF.getText();

        if (nama.isEmpty() || email.isEmpty() || telepon.isEmpty() || ktp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua data.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        boolean isTeleponValid = telepon.matches("\\d{10,}");
        String ktpRegex = "\\d{16,}"; 

        if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "Email harus menggunakan format 'example@company.com'.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isTeleponValid) {
            JOptionPane.showMessageDialog(this, "Nomor telepon harus terdiri dari 10 digit atau lebih.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!ktp.matches(ktpRegex)) {
            JOptionPane.showMessageDialog(this, "Nomor KTP harus terdiri dari minimal 16 digit.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Panggil constructor baru
        Booking booking = new Booking(nama, email, telepon, ktp);
        booking.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cariTiketB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariTiketB1;
    private javax.swing.JLabel detailtitleL;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel ktpL;
    private javax.swing.JTextField ktpTF;
    private javax.swing.JLabel namaL;
    private javax.swing.JTextField namaTF;
    private javax.swing.JLabel teleponL;
    private javax.swing.JTextField teleponTF;
    // End of variables declaration//GEN-END:variables
}
