/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.syavelanisrina.projectakhirpbo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asalTF = new javax.swing.JTextField();
        asalL = new javax.swing.JLabel();
        tujuanL = new javax.swing.JLabel();
        tanggalPergiL = new javax.swing.JLabel();
        penumpangL = new javax.swing.JLabel();
        tujuanTF = new javax.swing.JTextField();
        tanggalPergiTF = new javax.swing.JTextField();
        penumpangTF = new javax.swing.JTextField();
        cariTiketB = new javax.swing.JButton();
        tujuanPic = new javax.swing.JLabel();
        asalPic = new javax.swing.JLabel();
        penumpangPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        asalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalTFActionPerformed(evt);
            }
        });

        asalL.setText("Dari");

        tujuanL.setText("Ke");

        tanggalPergiL.setText("Tanggal Pergi");

        penumpangL.setText("Penumpang");

        tujuanTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuanTFActionPerformed(evt);
            }
        });

        tanggalPergiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalPergiTFActionPerformed(evt);
            }
        });

        penumpangTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penumpangTFActionPerformed(evt);
            }
        });

        cariTiketB.setText("Cari Tiket");
        cariTiketB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTiketBActionPerformed(evt);
            }
        });

        tujuanPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/project189-main/drawable-hdpi/location.png"))); // NOI18N

        asalPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/project189-main/drawable-hdpi/location.png"))); // NOI18N
        asalPic.setPreferredSize(new java.awt.Dimension(15, 20));

        penumpangPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syavelanisrina/projectakhirpbo/project189-main/drawable-ldpi/bottom_btn4.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tujuanPic)
                        .addComponent(asalPic, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(penumpangPic, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalPergiL)
                    .addComponent(penumpangL)
                    .addComponent(tujuanL)
                    .addComponent(asalL)
                    .addComponent(penumpangTF)
                    .addComponent(tanggalPergiTF)
                    .addComponent(asalTF)
                    .addComponent(tujuanTF))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(cariTiketB)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(asalL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asalPic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asalTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tujuanL)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tujuanPic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tujuanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(tanggalPergiL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalPergiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(penumpangL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(penumpangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(penumpangPic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(cariTiketB)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalTFActionPerformed
        String asal = asalTF.getText();
        asalTF.setText(asal.toUpperCase());
    }//GEN-LAST:event_asalTFActionPerformed

    private void tujuanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuanTFActionPerformed
        String tujuan = tujuanTF.getText();
        tujuanTF.setText(tujuan.toUpperCase());
    }//GEN-LAST:event_tujuanTFActionPerformed

    private void cariTiketBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTiketBActionPerformed
        if (asalTF.getText().isEmpty() || tujuanTF.getText().isEmpty() || tanggalPergiTF.getText().isEmpty() || penumpangTF.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harus diisi semua!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_cariTiketBActionPerformed

    private void tanggalPergiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalPergiTFActionPerformed
        String tanggalPergi = tanggalPergiTF.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        sdf.setLenient(false);
        
        try {
            Date date = sdf.parse(tanggalPergi);
            tanggalPergiTF.setText(sdf.format(date));
        } catch(ParseException e) {
            javax.swing.JOptionPane.showMessageDialog (this, "Tanggal tidak valid! Format tanggal dd-mm-yyyy.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            tanggalPergiTF.setText("");
        }
    }//GEN-LAST:event_tanggalPergiTFActionPerformed

    private void penumpangTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penumpangTFActionPerformed
        String penumpang = penumpangTF.getText();
        penumpangTF.setText(penumpang);
    }//GEN-LAST:event_penumpangTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asalL;
    private javax.swing.JLabel asalPic;
    private javax.swing.JTextField asalTF;
    private javax.swing.JButton cariTiketB;
    private javax.swing.JLabel penumpangL;
    private javax.swing.JLabel penumpangPic;
    private javax.swing.JTextField penumpangTF;
    private javax.swing.JLabel tanggalPergiL;
    private javax.swing.JTextField tanggalPergiTF;
    private javax.swing.JLabel tujuanL;
    private javax.swing.JLabel tujuanPic;
    private javax.swing.JTextField tujuanTF;
    // End of variables declaration//GEN-END:variables
}
