/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.syavelanisrina.projectakhirpbo;

/**
 *
 * @author ilham
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentlabel = new javax.swing.JLabel();
        tanggalabel = new javax.swing.JLabel();
        jamlabel = new javax.swing.JLabel();
        darilabel = new javax.swing.JLabel();
        kelabel = new javax.swing.JLabel();
        keretalabel = new javax.swing.JLabel();
        kelaslabel = new javax.swing.JLabel();
        totallabel = new javax.swing.JLabel();
        checkout = new javax.swing.JButton();
        isitanggal = new javax.swing.JLabel();
        isijam = new javax.swing.JLabel();
        isidari = new javax.swing.JLabel();
        isike = new javax.swing.JLabel();
        isikereta = new javax.swing.JLabel();
        isikelas = new javax.swing.JLabel();
        isitotal = new javax.swing.JLabel();
        backpayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paymentlabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        paymentlabel.setText("Payment");

        tanggalabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tanggalabel.setText("Tanggal");

        jamlabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jamlabel.setText("Jam");

        darilabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        darilabel.setText("Dari");

        kelabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        kelabel.setText("Ke");

        keretalabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        keretalabel.setText("Kereta");

        kelaslabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        kelaslabel.setText("Kelas");

        totallabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        totallabel.setText("Total");

        checkout.setBackground(new java.awt.Color(153, 255, 153));
        checkout.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        checkout.setForeground(new java.awt.Color(0, 0, 0));
        checkout.setText("Bayar");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        backpayment.setBackground(new java.awt.Color(255, 0, 0));
        backpayment.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        backpayment.setForeground(new java.awt.Color(0, 0, 0));
        backpayment.setText("Kembali");
        backpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backpaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(backpayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(darilabel)
                                .addComponent(kelabel)
                                .addComponent(keretalabel)
                                .addComponent(kelaslabel)
                                .addComponent(totallabel)
                                .addComponent(tanggalabel)
                                .addComponent(jamlabel))
                            .addComponent(paymentlabel))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isitanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isijam, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isidari, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isike, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isikereta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isikelas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isitotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(paymentlabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalabel)
                    .addComponent(isitanggal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jamlabel)
                    .addComponent(isijam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(darilabel)
                    .addComponent(isidari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelabel)
                    .addComponent(isike))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keretalabel)
                    .addComponent(isikereta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelaslabel)
                    .addComponent(isikelas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totallabel)
                    .addComponent(isitotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkout)
                    .addComponent(backpayment))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutActionPerformed

    private void backpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backpaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backpayment;
    private javax.swing.JButton checkout;
    private javax.swing.JLabel darilabel;
    private javax.swing.JLabel isidari;
    private javax.swing.JLabel isijam;
    private javax.swing.JLabel isike;
    private javax.swing.JLabel isikelas;
    private javax.swing.JLabel isikereta;
    private javax.swing.JLabel isitanggal;
    private javax.swing.JLabel isitotal;
    private javax.swing.JLabel jamlabel;
    private javax.swing.JLabel kelabel;
    private javax.swing.JLabel kelaslabel;
    private javax.swing.JLabel keretalabel;
    private javax.swing.JLabel paymentlabel;
    private javax.swing.JLabel tanggalabel;
    private javax.swing.JLabel totallabel;
    // End of variables declaration//GEN-END:variables
}
