package com.syavelanisrina.projectakhirpbo;

import javax.swing.JOptionPane;

public class Payment extends javax.swing.JFrame {
    private String nama, email, telepon, ktp, asal, tujuan, tanggal, namaKereta;
    private int harga, jumlahPenumpang;

    public Payment(String nama, String email, String telepon, String ktp, String asal, String tujuan, String tanggal, int harga, int jumlahPenumpang, String namaKereta) {
        this.nama = nama;
        this.email = email;
        this.telepon = telepon;
        this.ktp = ktp;
        this.asal = asal;
        this.tujuan = tujuan;
        this.tanggal = tanggal;
        this.harga = harga;
        this.jumlahPenumpang = jumlahPenumpang;
        this.namaKereta = namaKereta;
        initComponents();
        updatePaymentDetails();
    }
    
    public Payment(){
        initComponents();
    }

    
    private void updatePaymentDetails() {
        isitanggal.setText(tanggal);
        isidari.setText(asal);
        isike.setText(tujuan);
        isikereta.setText(namaKereta);
        isitotal.setText("Rp " + harga);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentlabel = new javax.swing.JLabel();
        tanggalabel = new javax.swing.JLabel();
        darilabel = new javax.swing.JLabel();
        kelabel = new javax.swing.JLabel();
        totallabel = new javax.swing.JLabel();
        checkout = new javax.swing.JButton();
        backpayment = new javax.swing.JButton();
        totallabel1 = new javax.swing.JLabel();
        isitanggal = new javax.swing.JLabel();
        isidari = new javax.swing.JLabel();
        isike = new javax.swing.JLabel();
        isikereta = new javax.swing.JLabel();
        isitotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paymentlabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        paymentlabel.setText("PAYMENT");

        tanggalabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tanggalabel.setText("Tanggal");

        darilabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        darilabel.setText("Dari");

        kelabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        kelabel.setText("Ke");

        totallabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        totallabel.setText("Kereta");

        checkout.setBackground(new java.awt.Color(153, 255, 51));
        checkout.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        checkout.setForeground(new java.awt.Color(0, 0, 0));
        checkout.setText("Bayar");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        backpayment.setBackground(new java.awt.Color(255, 0, 0));
        backpayment.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        backpayment.setForeground(new java.awt.Color(0, 0, 0));
        backpayment.setText("Kembali");
        backpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backpaymentActionPerformed(evt);
            }
        });

        totallabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        totallabel1.setText("Total");

        isitanggal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        isitanggal.setText("Tanggal");

        isidari.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        isidari.setText("Dari");

        isike.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        isike.setText("Ke");

        isikereta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        isikereta.setText("Kereta");

        isitotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        isitotal.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(kelabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(paymentlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(tanggalabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(isitanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(darilabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(isidari))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(isike))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(totallabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(isikereta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(totallabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(isitotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(backpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(paymentlabel)
                .addGap(46, 46, 46)
                .addComponent(tanggalabel)
                .addGap(6, 6, 6)
                .addComponent(isitanggal)
                .addGap(18, 18, 18)
                .addComponent(darilabel)
                .addGap(6, 6, 6)
                .addComponent(isidari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kelabel)
                .addGap(6, 6, 6)
                .addComponent(isike)
                .addGap(18, 18, 18)
                .addComponent(totallabel)
                .addGap(6, 6, 6)
                .addComponent(isikereta)
                .addGap(18, 18, 18)
                .addComponent(totallabel1)
                .addGap(6, 6, 6)
                .addComponent(isitotal)
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        JOptionPane.showMessageDialog(this, "Pembayaran berhasil! Terima kasih.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        StrukTiket struk = new StrukTiket(nama, telepon, asal, tujuan, tanggal, namaKereta, harga, jumlahPenumpang);
        struk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutActionPerformed

    private void backpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backpaymentActionPerformed
        JOptionPane.showMessageDialog(this, "Kembali ke daftar tiket.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_backpaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment("Nama", "Email", "Telepon", "KTP", "Bandung", "Jakarta", "12-12-2024", 250000, 2, "Kereta Papandayan").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backpayment;
    private javax.swing.JButton checkout;
    private javax.swing.JLabel darilabel;
    private javax.swing.JLabel isidari;
    private javax.swing.JLabel isike;
    private javax.swing.JLabel isikereta;
    private javax.swing.JLabel isitanggal;
    private javax.swing.JLabel isitotal;
    private javax.swing.JLabel kelabel;
    private javax.swing.JLabel paymentlabel;
    private javax.swing.JLabel tanggalabel;
    private javax.swing.JLabel totallabel;
    private javax.swing.JLabel totallabel1;
    // End of variables declaration//GEN-END:variables
}
