/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.syavelanisrina.projectakhirpbo;
import java.awt.Color;
import javax.swing.JButton;
/**
 *
 * @author shifa
 */
public class PilihKursi extends javax.swing.JFrame {
  
    private boolean[] kursiDipilih = new boolean[46];
    
    public PilihKursi() {
        initComponents();
        resetKursi();
    }
    
    private void resetKursi() {
        for (int i = 0; i < kursiDipilih.length; i++) {
            kursiDipilih[i] = false;
        }
    }
    
    private void pilihKursi (JButton kursiB, int nomorKursi) {
        kursiDipilih[nomorKursi - 1] = true;
        kursiB.setBackground(Color.DARK_GRAY);
        kursiB.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kursi1 = new javax.swing.JButton();
        kursi4 = new javax.swing.JButton();
        kursi8 = new javax.swing.JButton();
        kursi12 = new javax.swing.JButton();
        kursi16 = new javax.swing.JButton();
        kursi20 = new javax.swing.JButton();
        kursi24 = new javax.swing.JButton();
        kursi28 = new javax.swing.JButton();
        kursi32 = new javax.swing.JButton();
        kursi36 = new javax.swing.JButton();
        kursi40 = new javax.swing.JButton();
        kursi44 = new javax.swing.JButton();
        kursi5 = new javax.swing.JButton();
        kursi9 = new javax.swing.JButton();
        kursi13 = new javax.swing.JButton();
        kursi17 = new javax.swing.JButton();
        kursi21 = new javax.swing.JButton();
        kursi25 = new javax.swing.JButton();
        kursi29 = new javax.swing.JButton();
        kursi33 = new javax.swing.JButton();
        kursi37 = new javax.swing.JButton();
        kursi41 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        kursi3 = new javax.swing.JButton();
        kursi6 = new javax.swing.JButton();
        kursi10 = new javax.swing.JButton();
        kursi14 = new javax.swing.JButton();
        kursi18 = new javax.swing.JButton();
        kursi22 = new javax.swing.JButton();
        kursi26 = new javax.swing.JButton();
        kursi30 = new javax.swing.JButton();
        kursi34 = new javax.swing.JButton();
        kursi38 = new javax.swing.JButton();
        kursi42 = new javax.swing.JButton();
        kursi7 = new javax.swing.JButton();
        kursi11 = new javax.swing.JButton();
        kursi15 = new javax.swing.JButton();
        kursi19 = new javax.swing.JButton();
        kursi23 = new javax.swing.JButton();
        kursi27 = new javax.swing.JButton();
        kursi31 = new javax.swing.JButton();
        kursi35 = new javax.swing.JButton();
        kursi39 = new javax.swing.JButton();
        kursi43 = new javax.swing.JButton();
        kursi46 = new javax.swing.JButton();
        kursi2 = new javax.swing.JButton();
        kursi45 = new javax.swing.JButton();
        titlePilihKursiL = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kursi1.setText("1");
        kursi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi1ActionPerformed(evt);
            }
        });

        kursi4.setText("4");
        kursi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi4ActionPerformed(evt);
            }
        });

        kursi8.setText("8");
        kursi8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi8ActionPerformed(evt);
            }
        });

        kursi12.setText("12");
        kursi12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi12ActionPerformed(evt);
            }
        });

        kursi16.setText("16");
        kursi16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi16ActionPerformed(evt);
            }
        });

        kursi20.setText("20");
        kursi20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi20ActionPerformed(evt);
            }
        });

        kursi24.setText("24");
        kursi24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi24ActionPerformed(evt);
            }
        });

        kursi28.setText("28");
        kursi28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi28ActionPerformed(evt);
            }
        });

        kursi32.setText("32");
        kursi32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi32ActionPerformed(evt);
            }
        });

        kursi36.setText("36");
        kursi36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi36ActionPerformed(evt);
            }
        });

        kursi40.setText("40");
        kursi40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi40ActionPerformed(evt);
            }
        });

        kursi44.setText("44");
        kursi44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi44ActionPerformed(evt);
            }
        });

        kursi5.setText("5");
        kursi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi5ActionPerformed(evt);
            }
        });

        kursi9.setText("9");
        kursi9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi9ActionPerformed(evt);
            }
        });

        kursi13.setText("13");
        kursi13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi13ActionPerformed(evt);
            }
        });

        kursi17.setText("17");
        kursi17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi17ActionPerformed(evt);
            }
        });

        kursi21.setText("21");
        kursi21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi21ActionPerformed(evt);
            }
        });

        kursi25.setText("25");
        kursi25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi25ActionPerformed(evt);
            }
        });

        kursi29.setText("29");
        kursi29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi29ActionPerformed(evt);
            }
        });

        kursi33.setText("33");
        kursi33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi33ActionPerformed(evt);
            }
        });

        kursi37.setText("37");
        kursi37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi37ActionPerformed(evt);
            }
        });

        kursi41.setText("41");
        kursi41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi41ActionPerformed(evt);
            }
        });

        jButton23.setText("jButton1");

        kursi3.setText("3");
        kursi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi3ActionPerformed(evt);
            }
        });

        kursi6.setText("6");
        kursi6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi6ActionPerformed(evt);
            }
        });

        kursi10.setText("10");
        kursi10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi10ActionPerformed(evt);
            }
        });

        kursi14.setText("14");
        kursi14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi14ActionPerformed(evt);
            }
        });

        kursi18.setText("18");
        kursi18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi18ActionPerformed(evt);
            }
        });

        kursi22.setText("22");
        kursi22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi22ActionPerformed(evt);
            }
        });

        kursi26.setText("26");
        kursi26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi26ActionPerformed(evt);
            }
        });

        kursi30.setText("30");
        kursi30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi30ActionPerformed(evt);
            }
        });

        kursi34.setText("34");
        kursi34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi34ActionPerformed(evt);
            }
        });

        kursi38.setText("38");
        kursi38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi38ActionPerformed(evt);
            }
        });

        kursi42.setText("42");
        kursi42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi42ActionPerformed(evt);
            }
        });

        kursi7.setText("7");
        kursi7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi7ActionPerformed(evt);
            }
        });

        kursi11.setText("11");
        kursi11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi11ActionPerformed(evt);
            }
        });

        kursi15.setText("15");
        kursi15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi15ActionPerformed(evt);
            }
        });

        kursi19.setText("19");
        kursi19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi19ActionPerformed(evt);
            }
        });

        kursi23.setText("23");
        kursi23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi23ActionPerformed(evt);
            }
        });

        kursi27.setText("27");
        kursi27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi27ActionPerformed(evt);
            }
        });

        kursi31.setText("31");
        kursi31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi31ActionPerformed(evt);
            }
        });

        kursi35.setText("35");
        kursi35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi35ActionPerformed(evt);
            }
        });

        kursi39.setText("39");
        kursi39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi39ActionPerformed(evt);
            }
        });

        kursi43.setText("43");
        kursi43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi43ActionPerformed(evt);
            }
        });

        kursi46.setText("46");
        kursi46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi46ActionPerformed(evt);
            }
        });

        kursi2.setText("2");
        kursi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi2ActionPerformed(evt);
            }
        });

        kursi45.setText("45");
        kursi45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursi45ActionPerformed(evt);
            }
        });

        titlePilihKursiL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titlePilihKursiL.setText("Pilih Kursi");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kursi4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(kursi5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kursi8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kursi9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kursi44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kursi6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kursi1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(kursi2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kursi3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kursi7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursi46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(titlePilihKursiL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titlePilihKursiL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursi1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursi3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursi2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kursi6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kursi7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kursi11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi43, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kursi10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi45, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kursi4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kursi5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kursi9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi41, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kursi8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi36, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursi40, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kursi44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kursi7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi7ActionPerformed
        pilihKursi(kursi7, 7);
    }//GEN-LAST:event_kursi7ActionPerformed

    private void kursi11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi11ActionPerformed
        pilihKursi(kursi11, 11);
    }//GEN-LAST:event_kursi11ActionPerformed

    private void kursi15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi15ActionPerformed
        pilihKursi(kursi15, 15);
    }//GEN-LAST:event_kursi15ActionPerformed

    private void kursi19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi19ActionPerformed
        pilihKursi(kursi19, 19);
    }//GEN-LAST:event_kursi19ActionPerformed

    private void kursi23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi23ActionPerformed
        pilihKursi(kursi23, 23);
    }//GEN-LAST:event_kursi23ActionPerformed

    private void kursi27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi27ActionPerformed
        pilihKursi(kursi27, 27);
    }//GEN-LAST:event_kursi27ActionPerformed

    private void kursi31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi31ActionPerformed
        pilihKursi(kursi31, 31);
    }//GEN-LAST:event_kursi31ActionPerformed

    private void kursi35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi35ActionPerformed
        pilihKursi(kursi35, 35);
    }//GEN-LAST:event_kursi35ActionPerformed

    private void kursi39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi39ActionPerformed
        pilihKursi(kursi39, 39);
    }//GEN-LAST:event_kursi39ActionPerformed

    private void kursi43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi43ActionPerformed
        pilihKursi(kursi43, 43);
    }//GEN-LAST:event_kursi43ActionPerformed

    private void kursi46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi46ActionPerformed
        pilihKursi(kursi46, 46);
    }//GEN-LAST:event_kursi46ActionPerformed

    private void kursi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi1ActionPerformed
        pilihKursi(kursi1, 1);
    }//GEN-LAST:event_kursi1ActionPerformed

    private void kursi44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi44ActionPerformed
        pilihKursi(kursi44, 44);
    }//GEN-LAST:event_kursi44ActionPerformed

    private void kursi38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi38ActionPerformed
        pilihKursi(kursi38, 38);
    }//GEN-LAST:event_kursi38ActionPerformed

    private void kursi40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi40ActionPerformed
        pilihKursi(kursi40, 40);
    }//GEN-LAST:event_kursi40ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void kursi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi2ActionPerformed
        pilihKursi(kursi2, 2);
    }//GEN-LAST:event_kursi2ActionPerformed

    private void kursi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi3ActionPerformed
        pilihKursi(kursi3, 3);
    }//GEN-LAST:event_kursi3ActionPerformed

    private void kursi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi4ActionPerformed
        pilihKursi(kursi4, 4);
    }//GEN-LAST:event_kursi4ActionPerformed

    private void kursi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi5ActionPerformed
        pilihKursi(kursi5, 5);
    }//GEN-LAST:event_kursi5ActionPerformed

    private void kursi6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi6ActionPerformed
        pilihKursi(kursi6, 6);
    }//GEN-LAST:event_kursi6ActionPerformed

    private void kursi8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi8ActionPerformed
        pilihKursi(kursi8, 8);
    }//GEN-LAST:event_kursi8ActionPerformed

    private void kursi9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi9ActionPerformed
        pilihKursi(kursi9, 9);
    }//GEN-LAST:event_kursi9ActionPerformed

    private void kursi10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi10ActionPerformed
        pilihKursi(kursi10, 10);
    }//GEN-LAST:event_kursi10ActionPerformed

    private void kursi12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi12ActionPerformed
        pilihKursi(kursi12, 12);
    }//GEN-LAST:event_kursi12ActionPerformed

    private void kursi13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi13ActionPerformed
        pilihKursi(kursi13, 13);
    }//GEN-LAST:event_kursi13ActionPerformed

    private void kursi14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi14ActionPerformed
        pilihKursi(kursi14, 14);
    }//GEN-LAST:event_kursi14ActionPerformed

    private void kursi16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi16ActionPerformed
        pilihKursi(kursi16, 16);
    }//GEN-LAST:event_kursi16ActionPerformed

    private void kursi17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi17ActionPerformed
        pilihKursi(kursi17, 17);
    }//GEN-LAST:event_kursi17ActionPerformed

    private void kursi18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi18ActionPerformed
        pilihKursi(kursi18, 18);
    }//GEN-LAST:event_kursi18ActionPerformed

    private void kursi20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi20ActionPerformed
        pilihKursi(kursi20, 20);
    }//GEN-LAST:event_kursi20ActionPerformed

    private void kursi21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi21ActionPerformed
        pilihKursi(kursi21, 21);
    }//GEN-LAST:event_kursi21ActionPerformed

    private void kursi22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi22ActionPerformed
        pilihKursi(kursi22, 22);
    }//GEN-LAST:event_kursi22ActionPerformed

    private void kursi24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi24ActionPerformed
        pilihKursi(kursi24, 24);
    }//GEN-LAST:event_kursi24ActionPerformed

    private void kursi25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi25ActionPerformed
        pilihKursi(kursi25, 25);
    }//GEN-LAST:event_kursi25ActionPerformed

    private void kursi26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi26ActionPerformed
        pilihKursi(kursi26, 26);
    }//GEN-LAST:event_kursi26ActionPerformed

    private void kursi28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi28ActionPerformed
        pilihKursi(kursi28, 28);
    }//GEN-LAST:event_kursi28ActionPerformed

    private void kursi29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi29ActionPerformed
        pilihKursi(kursi29, 29);
    }//GEN-LAST:event_kursi29ActionPerformed

    private void kursi30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi30ActionPerformed
        pilihKursi(kursi30, 30);
    }//GEN-LAST:event_kursi30ActionPerformed

    private void kursi32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi32ActionPerformed
        pilihKursi(kursi32, 32);
    }//GEN-LAST:event_kursi32ActionPerformed

    private void kursi33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi33ActionPerformed
        pilihKursi(kursi33, 33);
    }//GEN-LAST:event_kursi33ActionPerformed

    private void kursi34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi34ActionPerformed
        pilihKursi(kursi34, 34);
    }//GEN-LAST:event_kursi34ActionPerformed

    private void kursi36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi36ActionPerformed
        pilihKursi(kursi36, 36);
    }//GEN-LAST:event_kursi36ActionPerformed

    private void kursi37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi37ActionPerformed
        pilihKursi(kursi37, 37);
    }//GEN-LAST:event_kursi37ActionPerformed

    private void kursi41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi41ActionPerformed
        pilihKursi(kursi41, 41);
    }//GEN-LAST:event_kursi41ActionPerformed

    private void kursi42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi42ActionPerformed
        pilihKursi(kursi42, 42);
    }//GEN-LAST:event_kursi42ActionPerformed

    private void kursi45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursi45ActionPerformed
        pilihKursi(kursi45, 45);
    }//GEN-LAST:event_kursi45ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihKursi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton23;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton kursi1;
    private javax.swing.JButton kursi10;
    private javax.swing.JButton kursi11;
    private javax.swing.JButton kursi12;
    private javax.swing.JButton kursi13;
    private javax.swing.JButton kursi14;
    private javax.swing.JButton kursi15;
    private javax.swing.JButton kursi16;
    private javax.swing.JButton kursi17;
    private javax.swing.JButton kursi18;
    private javax.swing.JButton kursi19;
    private javax.swing.JButton kursi2;
    private javax.swing.JButton kursi20;
    private javax.swing.JButton kursi21;
    private javax.swing.JButton kursi22;
    private javax.swing.JButton kursi23;
    private javax.swing.JButton kursi24;
    private javax.swing.JButton kursi25;
    private javax.swing.JButton kursi26;
    private javax.swing.JButton kursi27;
    private javax.swing.JButton kursi28;
    private javax.swing.JButton kursi29;
    private javax.swing.JButton kursi3;
    private javax.swing.JButton kursi30;
    private javax.swing.JButton kursi31;
    private javax.swing.JButton kursi32;
    private javax.swing.JButton kursi33;
    private javax.swing.JButton kursi34;
    private javax.swing.JButton kursi35;
    private javax.swing.JButton kursi36;
    private javax.swing.JButton kursi37;
    private javax.swing.JButton kursi38;
    private javax.swing.JButton kursi39;
    private javax.swing.JButton kursi4;
    private javax.swing.JButton kursi40;
    private javax.swing.JButton kursi41;
    private javax.swing.JButton kursi42;
    private javax.swing.JButton kursi43;
    private javax.swing.JButton kursi44;
    private javax.swing.JButton kursi45;
    private javax.swing.JButton kursi46;
    private javax.swing.JButton kursi5;
    private javax.swing.JButton kursi6;
    private javax.swing.JButton kursi7;
    private javax.swing.JButton kursi8;
    private javax.swing.JButton kursi9;
    private javax.swing.JLabel titlePilihKursiL;
    // End of variables declaration//GEN-END:variables
}
